name: "📦 Release new version"

on: push

permissions:
    id-token: write
    contents: write
    packages: write

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:

    build-artifacts:
        name: ${{matrix.icon}} build ${{ matrix.architecture }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                include:
                    -   architecture: aarch64-apple-darwin
                        os: macos-latest
                        icon: "🍏"
                    -   architecture: x86_64-apple-darwin
                        os: macos-latest-large
                        icon: "🍏"

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Rust
                uses: actions-rust-lang/setup-rust-toolchain@v1
                with:
                    toolchain: stable

            -   name: Add target
                run: rustup target add ${{ matrix.architecture }}

            -   name: Build
                run: cargo build --release --target ${{ matrix.architecture }}

            -   name: Create version tag for packaging
                id: version
                run: |
                    if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
                        echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
                    else
                        echo "version=dev-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
                    fi

            -   name: Package binary
                working-directory: target/${{ matrix.architecture }}/release
                run: |
                    tar -czvf brew-explorer-${{ steps.version.outputs.version }}-${{ matrix.architecture }}.tar.gz brew-explorer

            -   name: Generate SHA256
                id: sha256
                working-directory: target/${{ matrix.architecture }}/release
                run: |
                    HASH=$(shasum -a 256 brew-explorer-${{ steps.version.outputs.version }}-${{ matrix.architecture }}.tar.gz | cut -d ' ' -f 1)
                    echo "hash=$HASH" >> $GITHUB_OUTPUT
                    echo "SHA256: $HASH"

            -   name: Rename for architecture
                working-directory: target/${{ matrix.architecture }}/release
                run: mv brew-explorer brew-explorer-${{ matrix.architecture }}

            -   uses: actions/upload-artifact@v4
                with:
                    name: brew-explorer-${{ matrix.architecture }}
                    path: target/${{ matrix.architecture }}/release/brew-explorer-${{ matrix.architecture }}
                    if-no-files-found: error

            -   uses: actions/upload-artifact@v4
                with:
                    name: brew-explorer-${{ steps.version.outputs.version }}-${{ matrix.architecture }}.tar.gz
                    path: target/${{ matrix.architecture }}/release/brew-explorer-${{ steps.version.outputs.version }}-${{ matrix.architecture }}.tar.gz
                    if-no-files-found: error

            -   name: Output SHA256 Hash
                run: |
                    echo "🔐 SHA256 Hash for brew-explorer-${{ steps.version.outputs.version }}-${{ matrix.architecture }}.tar.gz:"
                    echo "${{ steps.sha256.outputs.hash }}"

    actual-release:
        name: Release artifacts
        runs-on: ubuntu-latest
        needs: build-artifacts

        steps:
            -   name: Download Artifacts
                uses: actions/download-artifact@v4
                with:
                    path: artifacts
                    merge-multiple: true

            -   name: List artifacts
                run: tree artifacts

            -   name: Create release
                uses: softprops/action-gh-release@v2
                if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
                with:
                    files: artifacts/**
                    make_latest: true
                    draft: false
                    prerelease: false
                    generate_release_notes: true
                    append_body: true
                    body: |
                        Brew Explorer - A terminal-based Homebrew package manager for listing, updating, and uninstalling packages.
                        
                        Released for the following architecture:
                        * 🍏aarch64-apple-darwin (macOS Silicon)
                        * 🍏x86_64-apple-darwin (macOS Intel)
